print ('Please enter the following information:')
first = input ('First name: ')
last = input ('Last name: ')
email = input ('Email address: ')
phone = input ('Phone Number: ')
job = input ('Job title: ')
id = input ('ID Number: ')
print ()
print ('The ID card is:')
print ('----------------------------------------------------------')
print (str last.upper() first.capitalize())
print(job.title())
print('ID: ' + id)
print()
print(email.lower)
print(phone)
print ('----------------------------------------------------------')
