print(' Please enter the following:')
print()
print()
adjective = input ('Adjective: ')
animal = input ('Animal: ')
verb_1 = input ('Verb: ')
exclamation = input ('Exclamation: ')
verb_2 = input ('Verb: ')
verb_3 = input ('Verb: ')
print()
print()
print('Your story is:')
print()
print()

print('The other day, I was really in trouble. It all started when I saw a very')
print(adjective +' '+ animal +' '+ verb_1 +' '+'down the hallway. "'+exclamation.capitalize()+'"! I yelled. But all')
print('I could think to do was to' + verb_2 + ' over and over. Miraculously,')
print('that caused it to stop, but not before it tried to'+verb_3)
print('right in front of my family.')