age = input('How old are you? ')
next = (int(age) + 1)
print('On your next birthday, you will be ' + str(next))
print()
egg = input ('How many egg cartons do you have?')
cartons = (int(egg)*12)
print('You have ' + str(cartons) + ' eggs')
print()
cookie = input('How many cookies do you have?')
people = input('How many people are there')
result = float(cookie)/float(people)
print('Each person may have '+ str(result) + ' cookies')