print('Please enter the following information:')
print()
name=input('First name:')
lname= input('Last name:')
email= input('Email Address:')
phone= input('Phone Number:')
job= input('Job Title:')
idnumber= input('ID Number:')
hair= input('Hair color:')
month= input('Birth Month: ')
eyes= input('Eyes Color: ')
training= input('Do you receive training?: ')
print()
print('The ID Card is:')
print('-----------------------------------')
print(str(lname.upper()+', ')+name.capitalize())
print(job.title())
print('ID: '+idnumber)
print()
print(email.lower())
print(phone)
print()
print(f'Hair: {hair.capitalize():15} Eyes: {eyes.capitalize()}')
print(f'Month: {month.capitalize():14} Training: {training.capitalize()}')
print('-----------------------------------')
